### ISSUE TITLE
predict() argument missing for 'cell_type_key' and 'condition_key'

### ISSUE THREAD

**Issue by gaelcge** [theislab/scgen#15]
Hi guys
I am not sure what arguments to pass to 'cell_type_key' and 'condition_key' following this error:

>>> pred, delta = scg.predict(adata= train_new, adata_to_predict=unperturbed_cd4t,
...                           conditions={"ctrl": "control", "stim":"stimulated"}) 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
TypeError: predict() missing 2 required positional arguments: 'cell_type_key' and 'condition_key'

Thanks

**Comment by gaelcge** [comment]
This worked = 

pred, delta = scg.predict(adata= train_new,conditions={"ctrl": "control", "stim":"stimulated"},cell_type_key="cell_type",condition_key="condition",adata_to_predict=unperturbed_cd4t)

**Comment by M0hammadL** [comment]
Hi, Thanks for mentioning, I update the example in the code.
