### ISSUE TITLE
Is the cell type label a must?

### ISSUE THREAD

**Issue by z625715875** [theislab/scgen#18]
Hi,

I am confused that why scgen needs to feed in the data with cell type labels. Does that means your scgen is a supervised learning method? Hoping your reply. Thank you.

**Comment by M0hammadL** [comment]
Hi, It does not need cell type labels for training, However, in the prediction step, you need to pass a certain cell type to `predict` function to transform it to your desired condition

**Comment by z625715875** [comment]
Thank you for your reply. I am sorry I did not make myself clear. I am quite interested in your method scgen applied to  integration of datasets. In in [this](https://nbviewer.jupyter.org/github/M0hammadL/scGen_notebooks/blob/master/notebooks/scgen_batch_removal.ipynb) example, the VAE network needs the cell type labels as a part of input. Does that mean batch removal based on scgen is a supervised learning algorithm as it need the cell type labels? As your method extremely outperforms other batch removal methods which do no need labels, I want to make sure whether your method uses additional information except for the gene expression matrix. Hoping your reply. Thanks a lot!

**Comment by M0hammadL** [comment]
Hey, sorry for the late reply:) yes it the case of batch removal it can be considered as supervised with respect to batch labels.

**Comment by z625715875** [comment]
Hi, can this method be considered as supervised with respect to **cell type labels** ?

**Comment by M0hammadL** [comment]
yes:)
