### ISSUE TITLE
Only runs on single core?

### ISSUE THREAD

**Issue by prete** [theislab/scgen#21]
Hi,
I'm trying to run the [scgen_batch_removal.ipynb example notebook](https://nbviewer.jupyter.org/github/M0hammadL/scGen_notebooks/blob/master/notebooks/scgen_batch_removal.ipynb) and currently only runs on a single core. In another environment it used to run using multiple cores but now I am not able to reproduce it. 

Is there something you could recommend?

Current logging.print_versions:
`scanpy==1.4.6 anndata==0.7.1 umap==0.3.10 numpy==1.17.0 scipy==1.3.0 pandas==0.24.2 scikit-learn==0.21.2 statsmodels==0.10.0 tensorflow==1.13.0-rc2 scgen==1.1.4`

Thank you!

**Comment by vkedlian** [comment]
Hi, 

I have the same issue with scgen batch removal notebook - it only uses a single core. Would be great if it is possible to speed it up by using multiple cores. 

Thanks a lot, 
Veronika

**Comment by M0hammadL** [comment]
Hi

Do you mean 



> Hi,
> I'm trying to run the [scgen_batch_removal.ipynb example notebook](https://nbviewer.jupyter.org/github/M0hammadL/scGen_notebooks/blob/master/notebooks/scgen_batch_removal.ipynb) and currently only runs on a single core. In another environment it used to run using multiple cores but now I am not able to reproduce it.
> 
> Is there something you could recommend?
> 
> Current logging.print_versions:
> `scanpy==1.4.6 anndata==0.7.1 umap==0.3.10 numpy==1.17.0 scipy==1.3.0 pandas==0.24.2 scikit-learn==0.21.2 statsmodels==0.10.0 tensorflow==1.13.0-rc2 scgen==1.1.4`
> 
> Thank you!


Hi,

Is the training slow or `scgen.batch_removal`?  because   `scgen.batch_removal()` mostly  uses cpu. 

Mo

**Comment by prete** [comment]
Training `network.train(train_data=train, n_epochs=100)`

**Comment by M0hammadL** [comment]
Would you please run it on  GPU? if it is CPU then it will be slow

**Comment by M0hammadL** [comment]
> Training `network.train(train_data=train, n_epochs=100)`

Would you please run it on GPU? if it is CPU then it will be slow

**Comment by prete** [comment]
Thank you for your answer @M0hammadL, sadly I don't have access to GPUs from this environment. 

I get that GPU will be faster, but can it be run on CPU using multiprocessing (more than one core)?

**Comment by M0hammadL** [comment]
I think it heavily depends on you configuration for multi-process, we have not explicitly used multiprocessing in the code. Can you get access to GPU? Maybe I can help. 

how big is your dataset?

**Comment by cartal** [comment]
Hi @M0hammadL , 

I've been using `scGen` on CPUs and it has definitely ran in multiple CPU's before. Using 500K cells with 10K HVGs on a machine with 30 CPUs this step took ~ 3 hrs, which is OK for now.

I have tried to run `scGen` on a GPU server in the past, but this didn't work. However, I'm happy to give it a try again. Can you provide some advice on the set up to run `scGen` on GPUs?

**Comment by M0hammadL** [comment]
> Hi @M0hammadL ,
> 
> I've been using `scGen` on CPUs and it has definitely ran in multiple CPU's before. Using 500K cells with 10K HVGs on a machine with 30 CPUs this step took ~ 3 hrs, which is OK for now.
> 
> I have tried to run `scGen` on a GPU server in the past, but this didn't work. However, I'm happy to give it a try again. Can you provide some advice on the set up to run `scGen` on GPUs?

Ok, I would say first Install `scgen` and then remove the tf installed by `scgen`. Next, install tensorflow-gpu and check whether `scgen` uses the GPU.
