### ISSUE TITLE
install error: ERROR: No matching distribution found for tensorflow==1.13

### ISSUE THREAD

**Issue by rlittman16** [theislab/scgen#23]
Hi,

I get this error when trying to install scGen:
ERROR: No matching distribution found for tensorflow==1.13

Additionally is there a conda package I could install? That would make installation easier.

Thanks!

**Comment by nahanoo** [comment]
Hi,

I manged to pull the right tensorflow version with pip using tensorflow==1.13.0rc2

Hope it's not too late.

Cheers

**Comment by nahanoo** [comment]
I just realize that I pointed you to a prelease versrion.

[tensorflow versoins](https://pypi.org/project/tensorflow/#history) Check here to get an overview of the versions.

**Comment by M0hammadL** [comment]
I think the problem is your python version, it has to be <=3.7
