### ISSUE TITLE
Keras 2.4.3 incompatibility with TensorFlow 2.1?

### ISSUE THREAD

**Issue by Lin-K76** [theislab/scgen#25]
Hi Theis Lab,

After creating a conda environment and installing only the scGen package, I tried to run "import scgen" as a test. However, I receive an error that seems like a package incompatibility: Keras requires TensorFlow 2.2 or higher. After installing TensorFlow 2.2, multiple other issues kept popping up so I reinstalled scgen. I then tried to downgrade only Keras to 2.3.0, which seemed to work and allowed me to run "import scgen" without compile errors. Will this still allow full scGen functionality? I am using Windows 10. Thank you!

**Comment by M0hammadL** [comment]
Hi @Lin-K76  thanks for pointing this out, yes it should be fine, I have also updated req to install keras 2.3
