### ISSUE TITLE
ImportError: cannot import name 'IndexMixin' from 'scipy.sparse.sputils'

### ISSUE THREAD

**Issue by levinhein** [theislab/scgen#28]
Hi. I'm having an import error. When I try to import scgen, I encounter the error below and attached as image. ALSO, whether I import scgen or scanpy alone, same "IndexMixin" error occurs. My scipy version is 1.5.2. I tried using version 1.4 and 1.2.1 (because I saw from other online issues that this should resolve it), but it didn't work for my case, the error is still the same. Help, please! 

`
ImportError: cannot import name 'IndexMixin' from 'scipy.sparse.sputils' (/home/levinbioinformatics/anaconda3/envs/scgen-env/lib/python3.7/site-packages/scipy/sparse/sputils.py)`

![image](https://user-images.githubusercontent.com/68268222/92985137-791dbe00-f4e2-11ea-8316-37866223487b.png)

**Comment by M0hammadL** [comment]
@levinhein  hi, I think it is not scgen problem, it is just an inconsistency in your env, I saw you posted an issue in scanpy too, try to change the version of scipy then it will be fixed.

**Comment by M0hammadL** [comment]
Hi

We have released a new PyTorch version of the code. Please use this version.

Best
Mo
