### ISSUE TITLE
Questions about  balancer function

### ISSUE THREAD

**Issue by SherleyWei** [theislab/scgen#31]
Hi, I found  that in the python file "util.py" in the models folder, the statement in the balancer function (line 190) that assigns values to balanced_data.obs[condition_key] is "balanced_data.obs[condition_key] = np.concatenate(all_ data_label)" , is this a misspelling or am I misunderstanding? I think it should be "balanced_data.obs[condition_key] = np.concatenate(all_data_condition)". I wonder if this has any effect on the results?

**Comment by M0hammadL** [comment]
Hi

We have released a new PyTorch version of the code. Please use this version.

Best
Mo
