### ISSUE TITLE
FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead   if not is_categorical(df_full[k]):

### ISSUE THREAD

**Issue by levinhein** [theislab/scgen#33]
Hello. I am running scGen on my project in Jupyter notebook then when I run the prediction part, I got a "FutureWarning". I wonder what this means and does it affect my scGen run and how to resolve it if it does? Thank you!

**SCRIPT:**
`unperturbed_cd4t = train[((train.obs["cell_type"] == "CD4T") & (train.obs["condition"] == "control"))]
`
**PROMPT:**
```
/home/levinbioinformatics/anaconda3/envs/scgen_test/lib/python3.7/site-packages/anndata/_core/anndata.py:1094: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  if not is_categorical(df_full[k]):
```

**Comment by M0hammadL** [comment]
Hi

We have released a new PyTorch version of the code. Please use this version.

Best
Mo
