### ISSUE TITLE
How to save scgen trained model?

### ISSUE THREAD

**Issue by levinhein** [theislab/scgen#36]
Hello. How can I save the scgen objects and scgen model? I have experienced running scgen 30hrs for three times because jupyter notebook crashed after training and during prediction.

I tried using pickle module to save the model (hoping that I could just load it again anytime instead or re-running scgen many times) but it doesn't seem to work and reverts an error. Advise, please. Thank you very much!

**Comment by M0hammadL** [comment]
Hi

We have released a new PyTorch version of the code. Please use this version.

Best
Mo
