### ISSUE TITLE
Bimodal data?

### ISSUE THREAD

**Issue by levinhein** [theislab/scgen#38]
Hello! I would like to ask for your advice/opinion about my results.

I integrated 2 independent scRNA-seq datasets from different studies using Seurat and then performed scGen. On the figure attached below, it appears that the R condition has 2 modes, which makes the prediction somewhere in between those modes. 

I wonder if you could give me advice on how to get a workaround on this, like whether this figure gives an insight that the two datasets are not compatible to be integrated to begin with. Or are there other tools which I can use to investigate this to resolve my prediction inaccuracy? 

![image](https://user-images.githubusercontent.com/68268222/98945665-c5f73280-252d-11eb-8667-c1ddd3c8acea.png)

![image](https://user-images.githubusercontent.com/68268222/98945875-15d5f980-252e-11eb-8461-9fd23ac8095d.png)

**Comment by HypoChloremic** [comment]
Are you using two independent datasets from different studies as input?

**Comment by levinhein** [comment]
Yes, 2 independent datasets from 2 different studies.

**Comment by levinhein** [comment]
Hello. Any comment on this?
