### ISSUE TITLE
Test all functionality in tests

### ISSUE THREAD

**Issue by adamgayoso** [theislab/scgen#44]

**Comment by Cottoneyejoe95** [comment]
Both notebooks run as intended. @M0hammadL is there any other functionality to test?

**Comment by M0hammadL** [comment]
not that I think of

**Comment by adamgayoso** [comment]
I meant to say we should add all functionality in the tests .py file so it runs with CI.

**Comment by M0hammadL** [comment]
@Cottoneyejoe95  then we need to add test functions for train, predict and batch removal functionalities

**Comment by Cottoneyejoe95** [comment]
I added the functions batch_removal, predict and reg_mean_plot into the test script
