### ISSUE TITLE
Tutorial Data gets not found?

### ISSUE THREAD

**Issue by Lesdormis** [theislab/scgen#47]
Hi, 

can you provide a new link or path for the training datasets in this tutorial 
https://scgen.readthedocs.io/en/latest/tutorials/scgen_perturbation_prediction.html
and this tutorial?
https://nbviewer.jupyter.org/github/M0hammadL/scGen_reproducibility/blob/master/Jupyter%20Notebooks/Fig2.ipynb

I got 404 for the 
train = sc.read("./tests/data/train_kang.h5ad",
                backup_url="https://goo.gl/33HtVh")
And couldn't find the corresponding dataset named as "train_pbmc.h5ad"

Thanks!

**Comment by jlduan** [comment]
Hi,

Thanks for developing this package. I have troubles downloading and repeating the tutorial too.

Best,

**Comment by M0hammadL** [comment]
@Cottoneyejoe95  would you please update the link for the data?

**Comment by Cottoneyejoe95** [comment]
Hi @Lesdormis and @jlduan ,
thanks for reporting this error. I updated the url for the file, so it should work now.

**Comment by bitcometz** [comment]
hi, I also cannot find the file `train_pbmc.h5ad` .
Could you help with this problem ?

Thanks !!!

**Comment by M0hammadL** [comment]
@Cottoneyejoe95  cold you please update the link
