### ISSUE TITLE
Please help with the train_pbmc.h5ad

### ISSUE THREAD

**Issue by bitcometz** [theislab/scgen#50]
hello,

I want to do the analysis in order to reproduce paper according to this notebook:
https://nbviewer.jupyter.org/github/M0hammadL/scGen_reproducibility/blob/master/Jupyter%20Notebooks/Fig2.ipynb

```
pbmc = sc.read("../data/train_pbmc.h5ad")
```

But I cannot find the `train_pbmc.h5ad` file. Could you help with this problem ?

Thanks!!!

**Comment by Cottoneyejoe95** [comment]
Hi,

there is a data downloader script in the reproducibility repo. Did you run that already?

https://github.com/theislab/scgen-reproducibility/blob/master/code/DataDownloader.py

**Comment by Cottoneyejoe95** [comment]
I will close the issue here, since it belongs to the other repo and you created the same issue there. :)
