### ISSUE TITLE
TypeError: Can't instantiate abstract class SCGEN with abstract methods setup_anndata

### ISSUE THREAD

**Issue by BrianLlll** [theislab/scgen#53]
Hi,
Thanks for your excellent contribution. I recently encountered a bug when I ran " scgen.SCGEN(train)". The error information is: 
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-47-0dbe34ca845e> in <module>()
----> 1 model = scgen.SCGEN(train)
      2 model.save("../model_batch_removal.pt", overwrite=True)

TypeError: Can't instantiate abstract class SCGEN with abstract methods setup_anndata

However, this code works well one week ago with the same data. Could you pls help me with this issue? Thank you.

Brian

**Comment by BrianLlll** [comment]
Hi @adamgayoso, 
I also followed your suggestion to copy the setup_anndata function and use this function to register the object. However, I still had the same issue when I ran "scgen.SCGEN(train)" with the same error information as before. Could you pls kindly provide some more help on this issue? Thank you.

**Comment by adamgayoso** [comment]
@SoloveyMaria @BrianLlll the solution I proposed is for developers of this package. For users, you just need to downgrade scvi-tools, using `pip3 install --upgrade scvi-tools==0.13.0`. This will temporarily fix your issue until the devs fix the package

**Comment by adamgayoso** [comment]
reopening

**Comment by minsu1794** [comment]
Hello I am following the tutorial and when I encountered the same issue followed the solution here:
 pip3 install --upgrade scvi-tools==0.13.0

However once I did this the error occur in preprocessing step:
scgen.SCGEN.setup_anndata(train_new, batch_key="condition", labels_key="cell_type")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: type object 'SCGEN' has no attribute 'setup_anndata'

Is there solution to this?
