### ISSUE TITLE
Normalization question for batch_removal

### ISSUE THREAD

**Issue by ryeking2010** [theislab/scgen#59]
Hello, thanks for such a great tool that's been [ranked as a high performer](https://www.nature.com/articles/s41592-021-01336-8)!

I am hoping to understand the normalization process.
In the [readme](https://github.com/theislab/scgen), it is mentioned to normalize the data as follows:
`import scanpy as sc
adata = sc.read(data)
sc.pp.normalize_total(adata)
sc.pp.log1p(adata)`

However, in the [tutorial](https://scgen.readthedocs.io/en/latest/tutorials/scgen_batch_removal.html), we see warning message:
corrected_adata = model.batch_removal()
WARNING  Make sure the registered X field in anndata contains unnormalized count data.

Should the data be normalized or contain raw counts if batch_removal() is run? Where would be the fix be made if unnormalized counts are used? model.X or train.X before/after training?

There's also the warning of filtering, if that could be addressed too, I think it would make the tutorial much more clearer.

Thanks!

**Comment by adamgayoso** [comment]
> Should the data be normalized or contain raw counts if batch_removal() is run?

The data should be normalized, please ignore that warning for now, we will update it soon.
