### ISSUE TITLE
pip install scanpy needs version bump

### ISSUE THREAD

**Issue by jvstokes** [theislab/scgen#62]
Following the scvi tools bump a couple days ago, looks like `pip install scgen` installation version does not work. The Nightly build still works fine.

Steps to reproduce:
- Create new environment
-`pip install scgen`
- running `import scgen` gives  `ImportError: cannot import name 'setup_anndata' from 'scvi.data'`

**Comment by adamgayoso** [comment]
@M0hammadL can you make a release on pypi?

Until another release is made this is the expected behavior.

**Comment by M0hammadL** [comment]
version 2.1 is out now https://pypi.org/manage/project/scgen/releases/ thanks @adamgayoso . sorry for the delay :)
