### ISSUE TITLE
ImportError: cannot import name 'setup_anndata' from 'scvi.data'

### ISSUE THREAD

**Issue by shangyf-stu** [theislab/scgen#64]
Hi,
Thanks for your nice work!
I want to run the tutorial for batch-removal, but some errors appear.
I have followed the installation tutorial to complete the installation, but do not install PyTorch.
When I am import scgen, I meet this ImportError.

And there is an error when downloading the data, a server exception occurs when the download is about to be completed

Best wishes,
Shang

**Comment by adamgayoso** [comment]
The tutorial and the docs are now up to date! Please ensure you install the master branch version.
