### ISSUE TITLE
AttributeError: module 'scgen' has no attribute 'VAEArith'

### ISSUE THREAD

**Issue by pcifist** [theislab/scgen#65]
I tried scgen-reproducibility (e.g. https://nbviewer.org/github/M0hammadL/scGen_reproducibility/blob/master/Jupyter%20Notebooks/Fig2.ipynb), but the error:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-19-661011a41207> in <module>
----> 1 network = scgen.VAEArith(z_dimension=100, 
      2                          x_dimension=pbmc.shape[1],
      3                          model_path="../models/scGen/pbmc/CD4T/scgen")
      4 network.restore_model()

AttributeError: module 'scgen' has no attribute 'VAEArith'
---------------------------------------------------------------------------
has been occured.
However, 'scgen' module import has been successful,  could you help with this problem?

**Comment by CocoGzh** [comment]
> ## I tried scgen-reproducibility (e.g. https://nbviewer.org/github/M0hammadL/scGen_reproducibility/blob/master/Jupyter%20Notebooks/Fig2.ipynb), but the error:
> AttributeError Traceback (most recent call last) in ----> 1 network = scgen.VAEArith(z_dimension=100, 2 x_dimension=pbmc.shape[1], 3 model_path="../models/scGen/pbmc/CD4T/scgen") 4 network.restore_model()
> 
> ## AttributeError: module 'scgen' has no attribute 'VAEArith'
> has been occured. However, 'scgen' module import has been successful, could you help with this problem?

I have the same question

**Comment by adamgayoso** [comment]
Please see the latest workflow here:

https://scgen.readthedocs.io/en/latest/

The API has changed recently.

**Comment by mzhang012130** [comment]
> Please see the latest workflow here:
> 
> https://scgen.readthedocs.io/en/latest/
> 
> The API has changed recently.

Thanks! I have read the workflow, but still confused on new API. So at this time, I should run scgen.SCGENVAE instead of scgen.VAEArith? But new error occurs while running the following line as AttributeError: 'SCGENVAE' object has no attribute 'predict_cross'. Could you shed more light on that?

**Comment by Maojie6509** [comment]
> > Please see the latest workflow here:
> > https://scgen.readthedocs.io/en/latest/
> > The API has changed recently.
> 
> Thanks! I have read the workflow, but still confused on new API. So at this time, I should run scgen.SCGENVAE instead of scgen.VAEArith? But new error occurs while running the following line as AttributeError: 'SCGENVAE' object has no attribute 'predict_cross'. Could you shed more light on that?

Hello, I have encountered the same problem. Could you tell me how to use SCGENVAE to build the model and how to predict it? Thanks
