### ISSUE TITLE
ImportError: cannot import name 'setup_anndata' from 'scvi.data'

### ISSUE THREAD

**Issue by GA-1101** [theislab/scgen#66]
Hi,
Thanks for your excellent contribution. I recently met an import issue: `cannot import name 'setup_anndata' from 'scvi.data'`

The initial script try to import 'setup_anndata' from the `*/scvi/data/__init__.py`.
It seems that the latest version of scvi-tools have no more 'setup_anndata' in '__init__.py'. It showed error:
`ImportError: cannot import name 'setup_anndata' from 'scvi.data'`

The latest version I installed of scvi-tools is '0.15.4', I downgrade the scvi-tools version to '0.9.0' so that the scgen can be import normally.

I think that may be an issue of the basic usage of scGen, could you please check the initial script and update related code to match the latest version of scvi-tools.

Lei

**Comment by adamgayoso** [comment]
Please see the latest tutorial: https://scgen.readthedocs.io/en/latest/tutorials/scgen_perturbation_prediction.html

The API changed slightly
