### ISSUE TITLE
missing dependencies

### ISSUE THREAD

**Issue by mumichae** [theislab/scgen#9]
keras seems to be missing when installing scgen for the first time

**Comment by mumichae** [comment]
same with `adjustText`

**Comment by M0hammadL** [comment]
@mumichae Hi, those are still left from old times, we will remove adjustText and add keras.

**Comment by M0hammadL** [comment]
I checked if you install it via pip all the dependencies like keras and ajdust-text are also installed.

https://github.com/theislab/scgen/blob/e2aaf55dd48adb68a63c812c7576f901ae69ba28/pyproject.toml#L19-L24

**Comment by mumichae** [comment]
oh right, I forgot to mention that I was installing it directly from the repo using `flit install` because I had made some changes to the code
